name: BuycraftDropParty
version: '${project.version}'
main: com.arr4nn.buycraftdropparty.BuycraftDropParty
api-version: 1.15
commands:
  beginDropEvent:
    permission: op
    description: "Begin the drop event"
